import {useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {Slider} from '@/components/ui/slider';
import {ArrowUpRight,RotateCcw,Move,Watch,ChevronRight,Layers,Play,Pause} from 'lucide-react';
import {parts,path} from './watch-data';
import {type SceneAPI} from './watch-scene';

export default function Home(){
 const [amount,setAmount]=useState(18),[selected,setSelected]=useState('balance'),[isolate,setIsolate]=useState(false),[view,setView]=useState('angle'),[ready,setReady]=useState(false),[error,setError]=useState(''),[playing,setPlaying]=useState(false),[cutaway,setCutaway]=useState(true),[showRotor,setShowRotor]=useState(false);
 useEffect(()=>{setPlaying(!window.matchMedia('(prefers-reduced-motion: reduce)').matches)},[]);
 function togglePlayback(){if(!playing)setIsolate(false);setPlaying(value=>!value)}
 const host=useRef<HTMLDivElement>(null), api=useRef<SceneAPI|null>(null); const current=parts.find(p=>p.id===selected)!;
 useEffect(()=>{let disposed=false; let cleanup:(()=>void)|undefined; import('./watch-scene').then(({WatchScene})=>{if(disposed||!host.current)return;try{api.current=WatchScene(host.current,id=>setSelected(id));cleanup=api.current.dispose;setReady(true)}catch(e){setError('The 3D view could not start. Please reload the page.');console.error(e)}});return()=>{disposed=true;cleanup?.()}},[]);
 useEffect(()=>{api.current?.setPlaying(playing)},[playing,ready]);
 useEffect(()=>{api.current?.update(amount,selected,isolate,view,cutaway,showRotor)},[amount,selected,isolate,view,cutaway,showRotor,ready]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context)return; const tool={name:'explore_watch',description:'Set the watch explosion from 0 to 100 and optionally select a named part.',inputSchema:{type:'object',properties:{percent:{type:'number',minimum:0,maximum:100},part:{type:'string',enum:parts.map(p=>p.id)}},required:['percent'],additionalProperties:false},execute:async({percent,part}:{percent:number,part?:string})=>{if(!Number.isFinite(percent)||percent<0||percent>100||(part&&!parts.some(p=>p.id===part)))throw Error('Invalid percent or part');flushSync(()=>{setAmount(percent);if(part)setSelected(part)});return {content:[{type:'text',text:JSON.stringify({percent,part:part||null})}]}}};context.registerTool(tool);return()=>context.unregisterTool?.('explore_watch')},[]);
 function choose(id:string){setSelected(id)}
 return <main><header><a className="brand" href="/"><Watch size={24}/><span>BLOWUP · SCOTT ALLISON SI</span></a><span className="edition">NO. 01 / MECHANICAL TIME</span><a className="source-link" href="#reference">About the model <ArrowUpRight size={14}/></a></header>
 <section className="intro"><div><p className="eyebrow">THE WATCHMAKER’S BENCH</p><h1>Time, <em>taken apart.</em></h1><p className="subtitle">Your time on the hands. A small world moving underneath.</p></div><div className="reference-badge"><span className="dot"/> NH35 REFERENCE<span>Simplified anatomy · original 3D model</span></div></section>
 <section className="workspace"><div className="studio"><div className="studio-top"><span><span className="dot"/> NH35 / EXPLORER</span><div className="view-buttons">{[['angle','Perspective'],['front','Dial'],['rear','Movement']].map(([id,label])=><button key={id} aria-pressed={view===id} onClick={()=>setView(id)}>{label}</button>)}<button aria-label="Reset view" onClick={()=>{setView('angle');setIsolate(false);setAmount(18);setSelected('balance');setCutaway(true);setShowRotor(false);api.current?.reset()}}><RotateCcw size={14}/></button></div></div>
 <div className="model-options"><label><input type="checkbox" checked={cutaway} onChange={e=>setCutaway(e.target.checked)}/> Reveal movement</label><label><input type="checkbox" checked={showRotor||selected==='rotor'} onChange={e=>{setShowRotor(e.target.checked);if(!e.target.checked&&selected==='rotor')setSelected('balance')}}/> Show rotor</label><span>{showRotor||selected==='rotor'?'Rotor visible':'Rotor tucked away'}</span></div><div className="viewport"><div ref={host} className="scene-host" aria-label="Interactive 3D exploded wristwatch"/>{!ready&&<div className="loading">{error||'Assembling the 3D watch…'}</div>}<div className="scene-caption"><span>01—12</span><span>{isolate?current.name:cutaway?'Cutaway illustration · dial and plate opened for visibility':'Full exterior · drag to look around'}</span></div></div>
 <div className="demo-row"><button className="demo-button" onClick={togglePlayback} disabled={!ready} aria-pressed={playing}>{playing?<Pause size={15}/>:<Play size={15}/>} {playing?'Pause':'Resume live time'}</button><LiveTime playing={playing}/></div><div className="interaction-hint"><Move size={13}/> Drag to orbit · Scroll to zoom · Click a part</div>
 <div className="explode"><div className="slider-title"><div><Layers size={17}/><strong>Open the watch</strong></div><output>{Math.round(amount)}<span>%</span></output></div><Slider aria-label="Exploded view" value={[amount]} onValueChange={v=>setAmount(Array.isArray(v)?v[0]:v)} min={0} max={100} step={1}/><div className="slider-stops"><button onClick={()=>{setAmount(0);setIsolate(false)}}>Assembled</button><button onClick={()=>{setAmount(50);setIsolate(false)}}>Peek inside</button><button onClick={()=>{setAmount(100);setIsolate(false)}}>Fully exploded</button></div></div></div>
 <aside><div className="inspector-label">EXPLORE THE ANATOMY <span>12 assemblies</span></div><article className="part-spotlight" key={selected}><span>{String(parts.findIndex(p=>p.id===selected)+1).padStart(2,'0')}</span><div><p>{current.tag}</p><h2>{current.name}</h2></div></article><article className="part-detail" aria-live="polite"><p>{current.text}</p><label className="isolate"><input type="checkbox" checked={isolate} onChange={e=>setIsolate(e.target.checked)}/> Show only this assembly</label><p className="note">{current.notice}</p></article><div className="part-grid">{parts.map((p,i)=><button key={p.id} aria-pressed={selected===p.id} onClick={()=>choose(p.id)}><span>{String(i+1).padStart(2,'0')}</span>{p.name}</button>)}</div></aside></section>
 <section className="power"><div><p className="eyebrow">FOLLOW THE ENERGY</p><h2>From your wrist<br/>to the hands.</h2><p>Choose a step to find it in the watch.</p></div><div className="power-path">{path.map((id,i)=><button key={id} className={selected===id?'active':''} onClick={()=>{choose(id);setAmount(75)}}><span>0{i+1} {i<5&&<ChevronRight size={14}/>}</span><strong>{['Capture','Wind','Store','Transmit','Regulate','Display'][i]}</strong><small>{['Rotor','Winding works','Mainspring','Gear train','Escapement & balance','Hands'][i]}</small></button>)}</div></section>
 <section id="reference" className="reference"><div><p className="eyebrow">THE REAL-WORLD REFERENCE</p><h2>A familiar workhorse.<br/>An extraordinary little machine.</h2><p>The TMI NH35 is a three-hand automatic movement with a date. This original 3D diagram uses its published specifications and parts documentation to explain the major assemblies.</p><p>This version uses no purchased assets. Geometry, gear positions and exploded spacing are simplified. Small levers, screws and some wheels are omitted. It is not manufacturer CAD, a complete replica, or a service manual.</p><div className="sources"><a href="https://timemodule.com/upload/category/24/spec_sheet/NH35_SS.pdf" target="_blank" rel="noreferrer">TMI specification <ArrowUpRight size={14}/></a><a href="https://timemodule.com/upload/category/24/technical_guide/NH35_TG.pdf" target="_blank" rel="noreferrer">TMI technical guide · June 2025 <ArrowUpRight size={14}/></a></div></div><div className="specs"><div><strong>27.4<span> mm</span></strong><p>Movement diameter</p></div><div><strong>5.32<span> mm</span></strong><p>Movement height</p></div><div><strong>24</strong><p>Jewels · low-friction bearings</p></div><div><strong>21,600</strong><p>Vibrations per hour · 3 Hz</p></div></div></section><footer>OBJECT LESSONS <span>Explore slowly. Everything has a part to play.</span></footer></main>
}

function LiveTime({playing}:{playing:boolean}){const [now,setNow]=useState(()=>new Date());useEffect(()=>{if(!playing)return;setNow(new Date());const timer=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(timer)},[playing]);return <div className="live-time"><time>{now.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false})}</time><span>{playing?'Your local time · live':'Time paused · resume to catch up'}<small>Internal motion is illustrative.</small></span></div>}
