import * as T from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {RoundedBoxGeometry} from 'three/examples/jsm/geometries/RoundedBoxGeometry.js';
import {mergeVertices} from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import {parts} from './watch-data';
import {watchMotion} from './watch-motion';
export type SceneAPI={update:(amount:number,selected:string,isolate:boolean,view:string,cutaway?:boolean,showRotor?:boolean)=>void,reset:()=>void,setPlaying:(playing:boolean)=>void,dispose:()=>void};
export function WatchScene(host:HTMLDivElement,onSelect:(id:string)=>void):SceneAPI{
 const scene=new T.Scene();const camera=new T.PerspectiveCamera(36,1,.1,400);camera.position.set(30,61,62);
 const renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.75));renderer.setClearColor(0x000000,0);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;host.appendChild(renderer.domElement);
 // A neutral studio with broad softboxes gives polished metal distinct reflections.
 const studio=new T.Scene();studio.background=new T.Color(0x65737f);
 for(const [x,y,z,w,h,intensity,color] of [[-18,24,12,14,30,5,0xffeedb],[20,8,-8,9,35,3,0xc2dcff],[0,35,-20,34,9,4,0xffffff],[0,-25,16,30,25,2,0xffffff]] as const){const panel=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({color,side:T.DoubleSide}));panel.material.color.multiplyScalar(intensity);panel.position.set(x,y,z);panel.lookAt(0,0,0);studio.add(panel)}
 const pmrem=new T.PMREMGenerator(renderer),env=pmrem.fromScene(studio,.035);scene.environment=env.texture;studio.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();(o.material as T.Material).dispose()}});pmrem.dispose();
 scene.add(new T.HemisphereLight(0xe1edf6,0x708787,1.1));const light=new T.DirectionalLight(0xffedda,2);light.position.set(-20,40,30);light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-45,right:45,top:45,bottom:-45,near:1,far:160});light.shadow.bias=-.0003;light.shadow.normalBias=.07;scene.add(light);
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.minDistance=23;controls.maxDistance=155;controls.enablePan=true;
 const finish=document.createElement('canvas');finish.width=256;finish.height=256;const ctx=finish.getContext('2d')!;ctx.fillStyle='#8f8f8f';ctx.fillRect(0,0,256,256);for(let i=0;i<256;i++){const v=120+((i*79)%47);ctx.fillStyle=`rgb(${v},${v},${v})`;ctx.fillRect(0,i,256,1)}const grain=new T.CanvasTexture(finish);grain.wrapS=grain.wrapT=T.RepeatWrapping;grain.repeat.set(.35,2);grain.anisotropy=4;
 const steel=new T.MeshStandardMaterial({color:0xc4ced6,metalness:.9,roughness:.3,roughnessMap:grain});
 const polished=new T.MeshStandardMaterial({color:0xf0f3f5,metalness:.94,roughness:.2});
 const gold=new T.MeshStandardMaterial({color:0xd4a756,metalness:.85,roughness:.23,roughnessMap:grain});
 const dark=new T.MeshStandardMaterial({color:0x091b22,metalness:.35,roughness:.4});
 const blue=new T.MeshPhysicalMaterial({color:0x16334f,metalness:.38,roughness:.3,clearcoat:.8,clearcoatRoughness:.22});
 const ruby=new T.MeshPhysicalMaterial({color:0xb41048,metalness:.25,roughness:.15,clearcoat:1});
 const glass=new T.MeshPhysicalMaterial({color:0xcde9eb,metalness:0,roughness:.025,transparent:true,opacity:.13,depthWrite:false,clearcoat:1,clearcoatRoughness:.02});
 const white=new T.MeshStandardMaterial({color:0xf0ecd9,roughness:.58});
 const groups:Record<string,T.Group>={}; const layers:Record<string,[number,number]>={crystal:[4.65,5.7],hands:[4.1,4.7],dial:[3.65,3.6],calendar:[3,2.4],plate:[2.3,1.2],barrel:[.9,0],train:[.9,0],balance:[.8,0],bridge:[0,-1.4],rotor:[-1.2,-2.8],back:[-2.3,-4.2],case:[.8,0]};
 for(const id of Object.keys(layers)){let g=new T.Group();g.userData.id=id;scene.add(g);groups[id]=g;}
 function mesh(g:T.Object3D,geo:T.BufferGeometry,mat:T.Material,x=0,y=0,z=0){let m=new T.Mesh(geo,mat.clone());m.castShadow=!mat.transparent;m.receiveShadow=!mat.transparent;m.position.set(x,y,z);g.add(m);return m}
 function disk(g:T.Object3D,r:number,h:number,mat:T.Material,x=0,y=0,z=0){return mesh(g,new T.CylinderGeometry(r,r,h,r>10?128:48),mat,x,y,z)}
 function ring(g:T.Object3D,r:number,inner:number,h:number,mat:T.Material,x=0,y=0,z=0,start=0,len=Math.PI*2){let s=new T.Shape();s.absarc(0,0,r,start,start+len,false);if(len<6.28){s.lineTo(inner*Math.cos(start+len),inner*Math.sin(start+len));s.absarc(0,0,inner,start+len,start,true);s.closePath()}else{let hole=new T.Path();hole.absarc(0,0,inner,0,Math.PI*2,true);s.holes.push(hole)}let geo:T.BufferGeometry=new T.ExtrudeGeometry(s,{depth:h,bevelEnabled:true,bevelSize:Math.min(.11,h*.2,(r-inner)*.2),bevelThickness:Math.min(.09,h*.18),bevelSegments:3,curveSegments:96});geo=mergeVertices(geo);geo.computeVertexNormals();geo.rotateX(-Math.PI/2);geo.translate(0,-h/2,0);return mesh(g,geo,mat,x,y,z)}
 function box(g:T.Object3D,w:number,h:number,d:number,mat:T.Material,x=0,y=0,z=0){return mesh(g,new RoundedBoxGeometry(w,h,d,3,Math.min(w,h,d)*.2),mat,x,y,z)}
 function screw(g:T.Object3D,x:number,y:number,z:number){disk(g,.44,.18,polished,x,y,z);box(g,.6,.035,.08,dark,x,y+.11,z)}
 function gear(g:T.Object3D,r:number,teeth:number,x:number,z:number,mat=gold){const unit=new T.Group();unit.position.set(x,0,z);g.add(unit);let shape=new T.Shape();for(let i=0;i<teeth*4;i++){let a=i/(teeth*4)*Math.PI*2,rr=r*(i%4===0||i%4===3?.89:1);if(i===0)shape.moveTo(Math.cos(a)*rr,Math.sin(a)*rr);else shape.lineTo(Math.cos(a)*rr,Math.sin(a)*rr)}shape.closePath();let hole=new T.Path();hole.absarc(0,0,r*.7,0,Math.PI*2,true);shape.holes.push(hole);let geo=new T.ExtrudeGeometry(shape,{depth:.32,bevelEnabled:true,bevelSize:.025,bevelThickness:.025,bevelSegments:2});geo.rotateX(-Math.PI/2);mesh(unit,geo,mat);for(let i=0;i<3;i++){let b=box(unit,r*1.5,.19,.26,mat);b.rotation.y=i*Math.PI/3}disk(unit,r*.22,.6,steel);return unit}
 function text(g:T.Object3D,words:string,w:number,d:number,x:number,y:number,z:number,color='#dae4e8',size=70){let c=document.createElement('canvas');c.width=512;c.height=128;let ctx=c.getContext('2d')!;ctx.fillStyle=color;ctx.font=`${size}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(words,256,64);let texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;let m=mesh(g,new T.PlaneGeometry(w,d),new T.MeshBasicMaterial({map:texture,transparent:true,depthWrite:false,side:T.DoubleSide}),x,y,z);m.rotation.x=-Math.PI/2;}
 const cg=groups.case;ring(cg,18.8,15,5.7,steel);ring(cg,19.1,16.35,.65,polished,0,3.05);ring(cg,18.85,18.5,.23,polished,0,-2.7);ring(cg,16.5,15.5,.9,dark,0,2.6);for(const x of [-11,11])for(const z of [-20,20]){let lug=box(cg,3.4,3.5,6.5,steel,x,-.1,z);lug.rotation.x=z>0?-.13:.13;}let crown=disk(cg,2.6,3.3,polished,21,0,0);crown.rotation.z=Math.PI/2;for(let i=0;i<28;i++){let a=i/28*Math.PI*2;box(cg,3.4,.18,.18,steel,21,Math.sin(a)*2.58,Math.cos(a)*2.58)}let stem=disk(cg,.45,8,steel,16,0,0);stem.rotation.z=Math.PI/2;
 ring(groups.crystal,16.15,15.95,.4,polished);disk(groups.crystal,15.96,.22,glass);
 ring(groups.back,18.5,12.8,.8,steel);disk(groups.back,12.8,.25,glass);for(let i=0;i<6;i++){let a=i*Math.PI/3;screw(groups.back,16.5*Math.cos(a),.5,16.5*Math.sin(a))}
 // Dial has a real aperture so the calendar is visible through it.
 let dialShape=new T.Shape();dialShape.absarc(0,0,15.5,0,Math.PI*2,false);let aperture=new T.Path();aperture.moveTo(10.2,-1.25);aperture.lineTo(13.1,-1.25);aperture.lineTo(13.1,1.25);aperture.lineTo(10.2,1.25);aperture.closePath();dialShape.holes.push(aperture);let dg=new T.ExtrudeGeometry(dialShape,{depth:.32,bevelEnabled:false,curveSegments:64});dg.rotateX(-Math.PI/2);const dialFace=mesh(groups.dial,dg,blue);const openDial=ring(groups.dial,15.5,13.2,.32,blue,0,.16);for(let i=0;i<60;i++){let a=i/60*Math.PI*2;if(i===15)continue;let major=i%5===0;let b=box(groups.dial,major?.35:.11,.08,major?1.45:.5,major?white:steel,Math.sin(a)*14,.39,-Math.cos(a)*14);b.rotation.y=-a;}const dialWriting=new T.Group();groups.dial.add(dialWriting);text(dialWriting,'ATELIER',6,1.5,0,.42,-5);text(dialWriting,'AUTOMATIC',5,1.1,0,.42,5);text(dialWriting,'NH35 REFERENCE',5,1,0,.42,6.4);
 const hands:T.Group[]=[];let handIndex=0;for(const [length,width,angle,mat] of [[8,.8,-Math.PI/3,white],[11,.55,Math.PI/3,white],[12.5,.16,Math.PI,gold]] as const){let h=new T.Group();groups.hands.add(h);hands.push(h);h.position.y=handIndex++*.17;h.rotation.y=-angle;box(h,width+.16,.12,length,polished,0,0,-length/2+1);box(h,width*.6,.025,length*.72,mat,0,.075,-length/2+1);disk(h,.58,.15,polished)}
 const dateRing=new T.Group();groups.calendar.add(dateRing);ring(dateRing,13.5,10,.35,white);for(let i=0;i<31;i++){let a=i/31*Math.PI*2;let g=new T.Group();g.position.set(Math.cos(a)*11.65,.23,Math.sin(a)*11.65);g.rotation.y=-a;dateRing.add(g);text(g,String(i+1),1.35,.9,0,0,0,'#151c20',84)}ring(groups.calendar,9.8,8.8,.23,steel);const calendarWheels=[gear(groups.calendar,2.1,22,3,4),gear(groups.calendar,1.5,18,0,1)];
 const plateFace=ring(groups.plate,13.7,2,.55,steel);const openPlate=ring(groups.plate,13.7,12.65,.55,steel);for(let i=0;i<8;i++){let a=i*Math.PI/4;disk(groups.plate,.4,.15,ruby,10*Math.cos(a),-.4,10*Math.sin(a));screw(groups.plate,11.8*Math.cos(a),.4,11.8*Math.sin(a))}
 const barrel=gear(groups.barrel,4.5,54,-6,-4);ring(barrel,3.9,3.55,1.05,gold,0,-.18);const points=[];for(let i=0;i<450;i++){let a=i/449*Math.PI*12,r=.4+3.05*i/449;points.push(new T.Vector3(Math.cos(a)*r,.35,Math.sin(a)*r))}barrel.add(new T.Line(new T.BufferGeometry().setFromPoints(points),new T.LineBasicMaterial({color:0xced3dc})));disk(barrel,.45,1.2,steel);
 const train=[gear(groups.train,3,40,.5,-4),gear(groups.train,2.3,32,4.5,-.8),gear(groups.train,1.9,26,2.5,3),gear(groups.train,1.35,15,6,5)];for(const [x,z] of [[.5,-4],[4.5,-.8],[2.5,3]])disk(groups.train,.24,.8,ruby,x,.3,z);
 const balanceWheel=new T.Group();balanceWheel.position.set(-5,0,6);groups.balance.add(balanceWheel);ring(balanceWheel,3.3,2.95,.32,gold);for(let i=0;i<3;i++){const spoke=box(balanceWheel,6,.22,.28,gold);spoke.rotation.y=i*Math.PI/3}disk(groups.balance,.4,.6,ruby,-5,0,6);
 const springPoints=[];for(let i=0;i<260;i++){const a=i/259*Math.PI*12,r=.25+2.25*i/259;springPoints.push(new T.Vector3(Math.cos(a)*r,.3,Math.sin(a)*r))}const hairspring=new T.Line(new T.BufferGeometry().setFromPoints(springPoints),new T.LineBasicMaterial({color:0x9fbcd6}));hairspring.position.set(-5,0,6);groups.balance.add(hairspring);
 const fork=new T.Group();fork.position.set(0,.1,5);groups.balance.add(fork);box(fork,4,.2,.35,steel);disk(fork,.3,.28,ruby,1.8,.05,-.3);
 // Partial bridges expose the train without implying a full engineering drawing.
 ring(groups.bridge,12.7,9.1,.6,steel,0,0,0,.1,Math.PI*1.1);box(groups.bridge,14,.6,2.3,steel,1,0,-3);box(groups.bridge,7,.6,2.5,steel,-6,0,4);for(const [x,z] of [[-10,-4],[7,-3],[9,6],[-6,4]])screw(groups.bridge,x,-.4,z);const winding=[gear(groups.bridge,3.6,44,0,0),gear(groups.bridge,2.2,25,5,2)];box(groups.bridge,4,.3,.55,steel,3,-.4,-1);
 ring(groups.rotor,13.25,9.7,.85,polished,0,0,0,Math.PI*.05,Math.PI*.95);let rotorShape=new T.Shape();rotorShape.moveTo(-11,0);rotorShape.lineTo(-8,-3);rotorShape.lineTo(0,-1);rotorShape.lineTo(8,-3);rotorShape.lineTo(11,0);rotorShape.lineTo(0,2);rotorShape.closePath();let rg=new T.ExtrudeGeometry(rotorShape,{depth:.5,bevelEnabled:true,bevelSize:.1,bevelThickness:.08,bevelSegments:3});rg.rotateX(-Math.PI/2);mesh(groups.rotor,rg,steel);ring(groups.rotor,1.7,.8,.8,polished);disk(groups.rotor,.75,.7,blue);for(let i=0;i<9;i++){let a=i/9*Math.PI*2;disk(groups.rotor,.16,.1,steel,1.2*Math.cos(a),.5,1.2*Math.sin(a))}
 function applyMotion(){const motion=watchMotion(elapsed,clockDate);groups.rotor.rotation.y=motion.rotor;barrel.rotation.y=motion.barrel;train.forEach((wheel,i)=>{wheel.rotation.y=motion.train[i]});winding.forEach((wheel,i)=>{wheel.rotation.y=motion.winding[i]});balanceWheel.rotation.y=motion.balance;hairspring.scale.set(motion.springScale,1,motion.springScale);fork.rotation.y=-.2+motion.fork;hands.forEach((hand,i)=>{hand.rotation.y=motion.hands[i]});calendarWheels[0].rotation.y=motion.hands[0];calendarWheels[1].rotation.y=-motion.hands[1];dateRing.rotation.y=motion.date;}
 const label=document.createElement('div');label.className='model-label';host.appendChild(label);
 const labelName=document.createElement('strong'),labelText=document.createElement('span');label.append(labelName,labelText);
 const shortDescriptions:Record<string,string>={crystal:'Protects the dial and hands.',hands:'Your local time, with a sweeping seconds hand.',dial:'Makes the time easy to read.',calendar:'Advances the date once each day.',plate:'Keeps the wheel pivots aligned.',barrel:'Stores energy in a coiled spring.',train:'Carries power through the movement.',balance:'Sets the rhythm of the mechanism.',bridge:'Supports the wheels and winds the spring.',rotor:'Turns wrist motion into stored energy.',back:'Protects the movement from behind.',case:'Houses the movement and setting crown.'};
 const callouts=['barrel','train','balance'].map(id=>{const el=document.createElement('button');el.className='part-pin';el.textContent=parts.find(p=>p.id===id)!.name;el.setAttribute('aria-label','Select '+el.textContent);el.addEventListener('click',()=>onSelect(id));host.appendChild(el);return {id,el}});
 const anchors:Record<string,T.Vector3>={barrel:new T.Vector3(-6,.5,-4),train:new T.Vector3(4.5,.5,-.8),balance:new T.Vector3(-5,.5,6)};
 const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
 let pending=0,disposed=false,targetAmount=18,shownAmount=18,selectedPart='balance',isolated=false,activeView='angle',playing=false,elapsed=0,previousTime=0,cutaway=true,showRotor=false;
 let clockDate=new Date();
 applyMotion();
 const targetCamera=camera.position.clone(),targetLook=new T.Vector3(0,3,0);let cameraMoving=false;
 function layout(){const e=shownAmount/100;for(const [id,g] of Object.entries(groups)){g.position.y=layers[id][0]+layers[id][1]*e*4;g.position.x=id==='case'?e*18:0;g.visible=!isolated||id===selectedPart;}
 groups.rotor.visible=(!isolated&&(showRotor||selectedPart==='rotor'))||(isolated&&selectedPart==='rotor');
 const reveal=cutaway&&!isolated;dialFace.visible=!reveal||selectedPart==='dial';openDial.visible=reveal&&selectedPart!=='dial';dialWriting.visible=dialFace.visible;plateFace.visible=!reveal||selectedPart==='plate';openPlate.visible=reveal&&selectedPart!=='plate';
 groups.crystal.visible=groups.crystal.visible&&(!reveal||selectedPart==='crystal');
 camera.zoom=Math.min(1,camera.aspect/1.12)*(isolated?1.3:1.14-e*.34);camera.updateProjectionMatrix();}
 function render(time=performance.now()){pending=0;if(disposed||document.hidden)return;if(playing&&previousTime&&time-previousTime<1000/30-1){invalidate();return}const dt=previousTime?Math.min(.05,(time-previousTime)/1000):0;previousTime=time;let moving=false;
 if(Math.abs(targetAmount-shownAmount)>.03){shownAmount=reducedMotion.matches?targetAmount:T.MathUtils.damp(shownAmount,targetAmount,13,dt);moving=true}else shownAmount=targetAmount;
 layout();if(cameraMoving){camera.position.lerp(targetCamera,reducedMotion.matches?1:1-Math.exp(-9*dt));controls.target.lerp(targetLook,reducedMotion.matches?1:1-Math.exp(-9*dt));controls.update();cameraMoving=camera.position.distanceTo(targetCamera)>.03||controls.target.distanceTo(targetLook)>.03;moving ||=cameraMoving;}
 if(playing){elapsed+=dt;clockDate=new Date();applyMotion();moving=true;}
 scene.updateMatrixWorld(true);const w=host.clientWidth,h=host.clientHeight;
 const anchor=(anchors[selectedPart]?groups[selectedPart].localToWorld(anchors[selectedPart].clone()):new T.Box3().setFromObject(groups[selectedPart]).getCenter(new T.Vector3())).project(camera);
 labelName.textContent=parts.find(p=>p.id===selectedPart)?.name||'';labelText.textContent=shortDescriptions[selectedPart]||'';
 const labelLeft=anchor.x>0?Math.min(w-122,(anchor.x*.5+.5)*w+100):Math.max(122,(anchor.x*.5+.5)*w-100);
 label.style.left=`${labelLeft}px`;label.style.top=`${Math.max(90,Math.min(h-95,(-anchor.y*.5+.5)*h+35))}px`;label.style.opacity=groups[selectedPart].visible?'1':'0';
 for(const {id,el} of callouts){const p=groups[id].localToWorld(anchors[id].clone()).project(camera);el.style.display=!isolated&&cutaway&&id!==selectedPart&&w>550?'block':'none';el.style.left=`${Math.max(80,Math.min(w-80,(p.x*.5+.5)*w+(id==='barrel'?-110:110)))}px`;el.style.top=`${Math.max(90,Math.min(h-50,(-p.y*.5+.5)*h+(id==='barrel'?-22:18)))}px`;}
 renderer.render(scene,camera);if(moving)invalidate();
 }
 function invalidate(){if(!pending&&!disposed&&!document.hidden)pending=requestAnimationFrame(render)}
 function onVisibility(){previousTime=0;if(document.hidden){cancelAnimationFrame(pending);pending=0}else invalidate()}
 document.addEventListener('visibilitychange',onVisibility);controls.addEventListener('change',invalidate);controls.addEventListener('start',()=>{cameraMoving=false});
 const observer=new ResizeObserver(()=>{const {width,height}=host.getBoundingClientRect();if(width&&height){renderer.setSize(width,height);camera.aspect=width/height;layout();invalidate()}});observer.observe(host);
 function update(amount:number,selected:string,isolate:boolean,view:string,reveal=true,rotorVisible=false){cutaway=reveal;showRotor=rotorVisible;targetAmount=amount;const selectionChanged=selected!==selectedPart||isolate!==isolated;selectedPart=selected;isolated=isolate;
 for(const [id,g] of Object.entries(groups))g.traverse(o=>{if(o instanceof T.Mesh){const mat=o.material as T.MeshStandardMaterial;if(mat.emissive){mat.emissive.set(id===selected?0xb9833b:0);mat.emissiveIntensity=id===selected?.045:0}}});
 if(view!==activeView||selectionChanged){activeView=view;const direction=new T.Vector3(...(view==='front'?[0,1,.001]:view==='rear'?[0,-1,.001]:[.3,.65,.65]) as [number,number,number]).normalize();let center=new T.Vector3(0,3,0);let distance=88;if(isolate){layout();const bounds=new T.Box3().setFromObject(groups[selected]);bounds.getCenter(center);distance=Math.max(30,bounds.getSize(new T.Vector3()).length()*1.7)}targetLook.copy(center);targetCamera.copy(center).addScaledVector(direction,distance);cameraMoving=true;}invalidate();
 }
 let down=[0,0];function pointerdown(e:PointerEvent){down=[e.clientX,e.clientY]}function pointerup(e:PointerEvent){if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=renderer.domElement.getBoundingClientRect();let ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);let hits=ray.intersectObjects(Object.values(groups).filter(g=>g.visible),true);let hit=hits.find(h=>{let m=(h.object as T.Mesh).material as T.MeshStandardMaterial;let o:T.Object3D|null=h.object;while(o){if(!o.visible)return false;o=o.parent}return !m?.transparent});if(hit){let o:T.Object3D|null=hit.object;while(o&&!o.userData.id)o=o.parent;if(o)onSelect(o.userData.id)}}renderer.domElement.addEventListener('pointerdown',pointerdown);renderer.domElement.addEventListener('pointerup',pointerup);controls.target.set(0,3,0);controls.update();invalidate();
 return {update,setPlaying(value){playing=value;if(value){clockDate=new Date();applyMotion()}previousTime=0;invalidate()},reset(){activeView='';update(18,'balance',false,'angle',true,false)},dispose(){disposed=true;cancelAnimationFrame(pending);observer.disconnect();document.removeEventListener('visibilitychange',onVisibility);label.remove();callouts.forEach(({el})=>el.remove());grain.dispose();controls.dispose();renderer.domElement.removeEventListener('pointerdown',pointerdown);renderer.domElement.removeEventListener('pointerup',pointerup);const geos=new Set<T.BufferGeometry>(),mats=new Set<T.Material>(),textures=new Set<T.Texture>();scene.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Line){geos.add(o.geometry);for(const mat of Array.isArray(o.material)?o.material:[o.material]){mats.add(mat);if(mat.map)textures.add(mat.map)}}});geos.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());env.dispose();renderer.dispose();renderer.domElement.remove()}};
}
