export const parts = [
{id:'crystal',name:'Crystal',tag:'The window',text:'A transparent cover protects the hands and dial. It belongs to the watch case, not the movement.',notice:'Glass is drawn with a faint blue edge so it stays visible when separated.'},
{id:'hands',name:'Hands',tag:'Make time readable',text:'The centre carries three concentric indicators. The motion works reduce the minute-hand rotation to one hour-hand revolution every 12 hours.',notice:'The hands show your device’s current local time. The seconds hand sweeps smoothly; the internal animation uses illustrative speeds.'},
{id:'dial',name:'Dial',tag:'The familiar face',text:'The dial hides most of the mechanism. A small opening at 3 o’clock reveals one number on the date ring beneath it.',notice:'Reveal movement opens a teaching cutaway in the dial. Switch it off to see the full face. This is an original case design.'},
{id:'calendar',name:'Date & motion works',tag:'One step each day',text:'A ring carries dates 1–31. The calendar mechanism advances it once a day; the motion works carry the hour and minute indication.',notice:'The ring is shown; the small calendar levers and the complete motion works are omitted.'},
{id:'plate',name:'Mainplate',tag:'The foundation',text:'The mainplate locates the moving parts. Its bearings and the bridges on the opposite side keep tiny wheel pivots aligned.',notice:'Reveal movement opens the mainplate for visibility. The cutaway and bridge outlines are simplified.'},
{id:'barrel',name:'Mainspring barrel',tag:'Store the energy',text:'A coiled steel spring stores energy inside a toothed drum. As the spring relaxes, the drum drives the going train. Winding replenishes that stored energy.',notice:'The open barrel exposes a schematic spring. A real barrel has a cover.'},
{id:'train',name:'Going train',tag:'Transmit the power',text:'A sequence of wheels and pinions carries torque from the barrel to the escapement. Different gear ratios also make the time indications possible.',notice:'Wheel positions, tooth counts and ratios are illustrative, not an exact NH35 gear layout.'},
{id:'balance',name:'Balance & escapement',tag:'Set the rhythm',text:'The balance and hairspring oscillate. The pallet fork locks and releases the escape wheel, giving the balance small impulses and metering the release of spring energy.',notice:'These parts share one learning group. The NH35 runs at 3 full balance oscillations per second; This illustration slows the balance to one oscillation per second so you can follow its motion.'},
{id:'bridge',name:'Bridges & winding works',tag:'Support and wind',text:'Bridges support wheel pivots. The automatic winding mechanism converts rotor movement into winding of the mainspring.',notice:'The winding wheels move in Play mode. Their speeds and the pawl-lever geometry are illustrative, not a working kinematic simulation.'},
{id:'rotor',name:'Automatic rotor',tag:'Your wrist is the input',text:'An off-centre mass turns as the watch moves. Through the winding mechanism it winds the mainspring, so ordinary wear can replenish the stored energy.',notice:'Hidden by default to keep the gear train visible. Select this part or enable Show rotor to bring it back. It winds the spring rather than directly driving the hands.'},
{id:'back',name:'Caseback',tag:'Close the shell',text:'The rear cover protects the movement. A display back lets you see the rotor and bridges, while the dial and most of the calendar remain on the other side.',notice:'Case shape, display glass and dimensions are illustrative; they are not NH35 movement specifications.'},
{id:'case',name:'Case & crown',tag:'Protect and control',text:'The case holds the movement. The crown connects to the setting stem: on the NH35 it allows hand winding, quick date adjustment and time setting with stop-seconds.',notice:'The crown and stem are shown as one simplified assembly. This viewer does not simulate crown operation.'}
];
export const path = ['rotor','bridge','barrel','train','balance','hands'];
